#!/usr/bin/env python3
"""
Convert a .pte (ExecuTorch) file to a C header file.

This creates a byte array that can be embedded directly in firmware,
avoiding the need for a filesystem on the microcontroller.

Usage:
    python pte_to_header.py model.pte model_pte.h
"""

import argparse
import sys
from pathlib import Path


def convert_pte_to_header(
    pte_path: Path,
    output_path: Path,
    array_name: str = "model_pte_data",
) -> None:
    """
    Convert a .pte file to a C header with the model as a byte array.
    
    Args:
        pte_path: Path to input .pte file
        output_path: Path to output .h file
        array_name: Name for the C array variable
    """
    if not pte_path.exists():
        print(f"Error: {pte_path} not found", file=sys.stderr)
        sys.exit(1)
    
    # Read binary data
    pte_data = pte_path.read_bytes()
    print(f"Read {len(pte_data)} bytes from {pte_path}")
    
    # Format as C hex array (12 bytes per line for readability)
    hex_bytes = [f"0x{b:02x}" for b in pte_data]
    lines = []
    bytes_per_line = 12
    
    for i in range(0, len(hex_bytes), bytes_per_line):
        line = ", ".join(hex_bytes[i : i + bytes_per_line])
        lines.append(f"    {line}")
    
    # Generate header content
    guard_name = output_path.stem.upper().replace(".", "_") + "_H"
    
    header_content = f"""/*
 * Auto-generated by pte_to_header.py
 * Source: {pte_path.name}
 * Size: {len(pte_data)} bytes
 * 
 * This file contains the ExecuTorch model as a byte array
 * for embedding in firmware.
 */

#ifndef {guard_name}
#define {guard_name}

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* Model data - aligned for efficient access */
static const uint8_t {array_name}[] __attribute__((aligned(8))) = {{
{',\\n'.join(lines)}
}};

/* Size of model data in bytes */
static const unsigned int {array_name.replace('_data', '_len')} = {len(pte_data)};

#ifdef __cplusplus
}}
#endif

#endif /* {guard_name} */
"""
    
    # Write output
    output_path.write_text(header_content)
    print(f"Generated {output_path} ({len(pte_data)} bytes embedded)")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert ExecuTorch .pte file to C header"
    )
    parser.add_argument(
        "pte_file",
        type=Path,
        help="Input .pte file"
    )
    parser.add_argument(
        "output_file",
        type=Path,
        nargs="?",
        default=None,
        help="Output .h file (default: <pte_name>.h)"
    )
    parser.add_argument(
        "--array-name",
        default="model_pte_data",
        help="Name for the C array (default: model_pte_data)"
    )
    
    args = parser.parse_args()
    
    # Default output name
    if args.output_file is None:
        args.output_file = args.pte_file.with_suffix(".h")
    
    convert_pte_to_header(args.pte_file, args.output_file, args.array_name)


if __name__ == "__main__":
    main()